#!/system/bin/sh
echo ========================================
echo ========== Storage Optimizing ==========
echo === it usually takes 5 to 10 minutes ===
echo ======= but can take 2-3 hours =========
echo ========================================
echo

for path in "/data" "/cache"
do
	echo ========= Optimizing $path  ============
	time busybox fstrim -v $path
	echo
done;

echo ========== DONE =============
